apiVersion: v1
kind: ConfigMap
metadata:
  name: obs-nginx-config
  namespace: obs-dev
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      log_format sre '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent rt=$request_time';
      access_log /var/log/nginx/access.log sre;
      server {
        listen 80;
        location / { root /usr/share/nginx/html; index index.html; }
        location /stub_status { stub_status; }
      }
    }
