apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obs-staging
resources:
  - namespace.yaml
  - ../obs-dev/nginx-config.yaml
  - ../obs-dev/deployment.yaml
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: obs-staging
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
  target:
    kind: Deployment
    name: obs-web
