apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - image-automation-logic.yaml
  - obs-dev.yaml
  - obs-staging.yaml
  - obs-prod.yaml
  - existing-logging.yaml
  - existing-monitoring.yaml
  - dev-app-sync.yaml
