name: FORCE-V11-SSH
on:
  push:
    branches: [ main ]
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: RUN-REMOTE-SCRIPT
        uses: appleboy/ssh-action@master
        with:
          host: 35.198.73.31
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export KUBECONFIG=/home/ondrejko_gulkas/.kube/config
            /home/ondrejko_gulkas/obs/ci/quality_gate.sh
