name: OBS-V21-DEPLOYMENT
on: [push]
jobs:
  gate-check:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-EXECUTE-V21
        uses: appleboy/ssh-action@master
        with:
          host: 34.159.144.113
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ondrejko_gulkas/obs
            git config --global --add safe.directory /home/ondrejko_gulkas/obs
            git pull origin main
            export KUBECONFIG=/home/ondrejko_gulkas/.kube/config
            ./ci/quality_gate.sh
