name: SSH-ONLY-PIPELINE
on:
  push:
    branches: [ main ]
jobs:
  run-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Remote Execution via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 35.198.73.31
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ondrejko_gulkas/obs
            export KUBECONFIG=/home/ondrejko_gulkas/.kube/config
            export PROM_URL="http://prometheus-server.monitoring.svc.cluster.local:9090"
            export ES_URL="http://elasticsearch.logging.svc.cluster.local:9200"
            export NAMESPACE="obs-dev"
            chmod +x ci/quality_gate.sh
            ./ci/quality_gate.sh
