name: OBS-PROD-PIPELINE
on: [push]
jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Execution
        uses: appleboy/ssh-action@master
        with:
          host: 35.198.73.31
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ondrejko_gulkas/obs
            git config --global --add safe.directory /home/ondrejko_gulkas/obs
            git pull origin main
            
            # Use 'prometheus' instead of 'prometheus-server'
            export KUBECONFIG=/home/ondrejko_gulkas/.kube/config
            export PROM_URL="http://prometheus.monitoring.svc.cluster.local:9090"
            export ES_URL="http://elasticsearch.logging.svc.cluster.local:9200"
            export NAMESPACE="obs-dev"
            
            ./ci/quality_gate.sh
