name: V12-SUPER-RESET
on: [push]
jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-CONNECTION
        uses: appleboy/ssh-action@master
        with:
          host: 35.198.73.31
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pripojenie uspesne, zistujem stav klastra..."
            # Explicitne nastavenie cesty ku klastru
            export KUBECONFIG=/home/ondrejko_gulkas/.kube/config
            
            kubectl get nodes
            echo "--- Pody v OBS-DEV ---"
            kubectl get pods -n obs-dev
