name: V12-SUPER-RESET
on: [push]
jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-CONNECTION
        uses: appleboy/ssh-action@master
        with:
          host: 35.198.73.31
          username: ondrejko_gulkas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Ak toto vidis v logu na Githube, vyhrali sme!"
            hostname
            kubectl get nodes
